### ISSUE TITLE
Epoch.min.js 

### ISSUE THREAD

**Issue by kswain1** [RussTheAerialist/imuduino-3js#4]
Currently have downloaded the imuduino library, and I am trying to run gulp, but ran into the problem? It is having a problem finding the epoch module. What epoch module is used with this project?

![screen shot 2016-02-29 at 4 53 14 pm](https://cloud.githubusercontent.com/assets/9138420/13411832/0d2fcdfc-df05-11e5-8cf1-e08c843c43c2.png)

**Comment by graysonarts** [comment]
epoch is included as a git submodule.  You'll need to do the following from your clone root:
`git submodule update --init --recursive`

**Comment by kswain1** [comment]
Thank You! For actively managing your repo. However I am having one more problem when trying to add the submodule I am getting the error below.

![screen shot 2016-02-29 at 5 54 07 pm](https://cloud.githubusercontent.com/assets/9138420/13413080/7f155b8c-df0d-11e5-9feb-529a59f3357d.png)

**Comment by kswain1** [comment]
Is this just cloning the epoch library into your file.

**Comment by kswain1** [comment]
the epoch library has been change to this link https://github.com/epochjs/epoch . May need to update this in the submodule because the link you have given leads to a dead end.
