### ISSUE TITLE
Changing the cube object

### ISSUE THREAD

**Issue by kswain1** [RussTheAerialist/imuduino-3js#5]
Hey I am currently editing the client/pyr.js. Added the CylinderGeometry to the pyr.js instead of cube. However the cylinder shape is not showing, but the square shape still remains as the scene object.  

`var geometry = new three.CylinderGeometry(1, 1, 1),
    material = new three.MeshLambertMaterial( { color: 0xFF6600 }),
    cube = new three.Mesh(geometry, material)`

When I looked at the source on the web I the html calling the source file of 
'script src="pyr-3784de6bfe.js"></script'

But I cannot find this file in the repository. Do you know what is happening? Thanks for the help.

**Comment by graysonarts** [comment]
Did you rerun gulp?  Gulp combines the various Javascript files into a
single JS file, so you need to rerun gulp when you make changes.

**Comment by kswain1** [comment]
Thanks that worked!
